### ISSUE TITLE
[Server] Loot does not de-spawn

### ISSUE THREAD

**Issue by ComradeSythar** [HebiKotei/DecayRP#2]
name: [Server] Loot does not de-spawn
about: Loot does not de-spawn
title: [Server] Loot does not de-spawn
labels: bug
assignees: ''

---

Describe the bug
Loot dropped on the ground does not despawn

To Reproduce

pick up loot
drop on ground
exit game
come back next day
all loot still there

Screenshots

![20211216211107_1](https://user-images.githubusercontent.com/96264306/146487808-f66ae063-041a-4917-a985-38289c22c925.jpg)

If this issue needs to be further explored I can do what I can to help

**Comment by YvanCywan** [comment]
Please update this report so that it fits the title description in the README.me, and to please use the template found in the box when opening the template.

**Comment by ComradeSythar** [comment]
I would like to note that I was able to confirm that loot still does not de-spawn.  As can be seen in below screenshot. The rotten remains are from the wolves killed around 48 hours prior.

![20211221145638_1](https://user-images.githubusercontent.com/96264306/147002865-9ad4a680-384b-40e9-a08e-0938acdb53a9.jpg)

**Comment by YvanCywan** [comment]
https://github.com/HebiKotei/DRP_Mission.chernarusplus/commit/019303d0e79209030a8ed2eab7613e8cf8e24a01

Issue should now be resolved as of the next server restart.
