### ISSUE TITLE
[Server] Invisible plate carrier spawn

### ISSUE THREAD

**Issue by ComradeSythar** [HebiKotei/DecayRP#3]
Describe the bug
Invisible plate carrier spawned and able to be looted. The location found was in a connex box south side of Tishina dam. 

To Reproduce

I do not know loot mechanics to be able to help on reproducing the issue

Screenshots
(https://media.discordapp.net/attachments/925626329163005982/925626660441710662/unknown.png?width=913&height=514)

Additional context

**Comment by YvanCywan** [comment]
I removed the only other conflict that could've caused this, awaiting testing now

**Comment by YvanCywan** [comment]
Closing this now, if the issue persists please open a new ticker.
